package com.javacreed.api.axon.command;

/**
 * The caller can stop listening for the events generated by the command through this handle. This handle will not
 * interrupt the command, but simply stops listening. The {@link Callback#apply(Object)} method will not be invoked if
 * the ignore handle is invoke before.
 *
 * @author Albert Attard
 * @see Callback
 */
public interface IgnoreHandle {

  /**
   * Stop listening for the events generated by the command without interrupting or stopping the command itself
   */
  void ignore();
}
